# Generated by Django 6.1.1 on 2026-09-16 10:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor_type', models.CharField(choices=[('USER', 'User'), ('SYSTEM', 'System'), ('ANONYMOUS', 'Anonymous')], max_length=9)),
                ('action', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='action must be a lowercase dotted identifier', regex='^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$')])),
                ('outcome', models.CharField(choices=[('SUCCESS', 'Success'), ('DENIED', 'Denied'), ('FAILED', 'Failed')], max_length=7)),
                ('target_type', models.CharField(blank=True, max_length=128, null=True, validators=[django.core.validators.RegexValidator(message='target_type must be a lowercase dotted identifier', regex='^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$')])),
                ('target_id', models.CharField(blank=True, max_length=255, null=True)),
                ('request_id', models.UUIDField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('user_agent_summary', models.CharField(blank=True, max_length=256, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('actor_user', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
                'default_permissions': (),
                'indexes': [models.Index(fields=['-occurred_at'], name='audit_evt_occurred_idx'), models.Index(fields=['action', '-occurred_at'], name='audit_evt_action_time_idx'), models.Index(fields=['actor_user', '-occurred_at'], name='audit_evt_actor_time_idx'), models.Index(fields=['target_type', 'target_id', '-occurred_at'], name='audit_evt_target_time_idx'), models.Index(fields=['request_id'], name='audit_evt_request_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('actor_type', 'USER'), ('actor_user__isnull', False)), models.Q(('actor_type__in', ['SYSTEM', 'ANONYMOUS']), ('actor_user__isnull', True)), _connector='OR'), name='audit_event_actor_valid'), models.CheckConstraint(condition=models.Q(('outcome__in', ['SUCCESS', 'DENIED', 'FAILED'])), name='audit_event_outcome_valid'), models.CheckConstraint(condition=models.Q(('action__regex', '^[a-z][a-z0-9]*(?:\\.[a-z][a-z0-9]*)+$')), name='audit_event_action_format'), models.CheckConstraint(condition=models.Q(models.Q(('target_type__isnull', True), ('target_id__isnull', True)), models.Q(('target_type__isnull', False), ('target_id__isnull', False)), _connector='OR'), name='audit_event_target_pair')],
            },
        ),
    ]
