# Generated by Django 6.1.1 on 2026-09-16

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("audit", "0002_alter_auditevent_metadata"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="auditevent",
            name="audit_event_action_format",
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                max_length=128,
                validators=[
                    django.core.validators.RegexValidator(
                        message="action must be a lowercase dotted identifier",
                        regex=r"^[a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)+$",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(("action__regex", r"^[a-z][a-z0-9_]*(?:\.[a-z][a-z0-9_]*)+$")),
                name="audit_event_action_format",
            ),
        ),
    ]
