# Generated by Django 6.1.1 on 2026-09-16 10:55

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('mfa_verified_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent_summary', models.CharField(blank=True, max_length=256, null=True)),
                ('initial_ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('created_request_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authentication_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_used_at', '-created_at', '-id'),
                'default_permissions': (),
                'indexes': [models.Index(fields=['user', 'revoked_at', 'expires_at'], name='auth_session_active_idx'), models.Index(fields=['expires_at'], name='auth_session_expiry_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='auth_session_expiry_after_creation')],
            },
        ),
        migrations.CreateModel(
            name='EmailOTPChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('purpose', models.CharField(choices=[('email_verification', 'Email verification'), ('recovery', 'Recovery'), ('security_challenge', 'Security challenge')], max_length=32)),
                ('code_hash', models.CharField(editable=False, max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expires_at', models.DateTimeField()),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempt_count', models.PositiveIntegerField(default=0)),
                ('send_count', models.PositiveIntegerField(default=1)),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_otp_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'default_permissions': (),
                'indexes': [models.Index(fields=['email', 'purpose', 'expires_at'], name='auth_email_otp_lookup_idx'), models.Index(fields=['user', 'expires_at'], name='auth_email_otp_user_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='auth_email_otp_expiry_after_creation')],
            },
        ),
        migrations.CreateModel(
            name='LoginChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('expires_at', models.DateTimeField()),
                ('primary_credentials_verified_at', models.DateTimeField(editable=False)),
                ('allowed_methods', models.JSONField(default=list)),
                ('trust_browser', models.BooleanField(default=False)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent_summary', models.CharField(blank=True, max_length=256, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('created_request_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'default_permissions': (),
                'indexes': [models.Index(fields=['user', 'expires_at'], name='auth_challenge_user_idx'), models.Index(fields=['expires_at'], name='auth_challenge_expiry_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='auth_challenge_expiry_after_creation')],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('code_hash', models.CharField(editable=False, max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'default_permissions': (),
                'indexes': [models.Index(fields=['user', 'used_at', 'invalidated_at'], name='auth_recovery_active_idx'), models.Index(fields=['user', 'batch_id'], name='auth_recovery_batch_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('used_at__isnull', True), ('invalidated_at__isnull', True), _connector='OR'), name='auth_recovery_one_terminal_state')],
            },
        ),
        migrations.CreateModel(
            name='TOTPFactor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('encrypted_secret', models.TextField(editable=False, max_length=512)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('last_verified_time_step', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totp_factors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(condition=models.Q(('disabled_at__isnull', True)), fields=('user',), name='auth_one_active_totp_per_user'), models.CheckConstraint(condition=models.Q(('disabled_at__isnull', True), ('confirmed_at__isnull', False), _connector='OR'), name='auth_disabled_totp_was_confirmed')],
            },
        ),
        migrations.CreateModel(
            name='TrustedSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_digest', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user_agent_summary', models.CharField(blank=True, max_length=256, null=True)),
                ('created_ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('last_ip_address', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True)),
                ('created_request_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_authentication_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_used_at', '-created_at', '-id'),
                'default_permissions': (),
                'indexes': [models.Index(fields=['user', 'revoked_at', 'expires_at'], name='auth_trusted_active_idx'), models.Index(fields=['expires_at'], name='auth_trusted_expiry_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='auth_trusted_expiry_after_creation')],
            },
        ),
    ]
