# Generated by Django 6.1.1 on 2026-09-16 09:23

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('code',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('code',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('code',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('suffix', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('profile_photo_object_key', models.CharField(blank=True, max_length=512, null=True)),
                ('profile_photo_updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role')),
            ],
            options={
                'ordering': ('-created_at',),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='UserDesignation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_assignments', to='accounts.designation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designation_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='designations',
            field=models.ManyToManyField(blank=True, related_name='users', through='accounts.UserDesignation', to='accounts.designation'),
        ),
        migrations.CreateModel(
            name='DesignationCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='designation_grants', to='accounts.capability')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capability_grants', to='accounts.designation')),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('designation', 'capability'), name='accounts_designation_capability_uniq')],
            },
        ),
        migrations.CreateModel(
            name='RoleCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_grants', to='accounts.capability')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capability_grants', to='accounts.role')),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('role', 'capability'), name='accounts_role_capability_uniq')],
            },
        ),
        migrations.CreateModel(
            name='UserCapabilityOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(choices=[('GRANT', 'Grant'), ('REVOKE', 'Revoke')], max_length=6)),
                ('reason', models.CharField(max_length=500)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_overrides', to='accounts.capability')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_capability_overrides', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'default_permissions': (),
                'constraints': [models.UniqueConstraint(fields=('user', 'capability'), name='accounts_user_capability_override_uniq'), models.CheckConstraint(condition=models.Q(('effect__in', ['GRANT', 'REVOKE'])), name='accounts_override_effect_valid')],
            },
        ),
        migrations.AddConstraint(
            model_name='userdesignation',
            constraint=models.UniqueConstraint(fields=('user', 'designation'), name='accounts_user_designation_uniq'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='accounts_user_email_ci_uniq'),
        ),
    ]
